on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'vkurko/calendar'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: create pr and publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
